export const projects = [
  {
    tags: ["IoT", "Mobile", "AI"],
    title: "SmartQuit",
    desc: "Wearable smoking cessation aid with real-time edge detection",
    thumbnail: "/thumbnails/smartquit.png",
    tech: ["Flutter", "TensorFlow Lite", "C++ (Embedded)"],
    github: "https://github.com/ShreyNagda/smartquit",
    live: "",
  },
  {
    tags: ["Fullstack", "Web"],
    title: "StaticSend",
    desc: "A backendless form provider for static sites",
    thumbnail: "/thumbnails/staticsend.png", // Using the high-quality mockup
    tech: ["Next JS", "TypeScript", "MongoDB", "Tailwind CSS"],
    github: "https://github.com/ShreyNagda/staticsend",
    live: "https://staticsend.vercel.app/",
  },
  {
    tags: ["Mobile", "Productivity"],
    title: "Focal",
    desc: "A minimalistic productivity and focus timer",
    thumbnail: "/thumbnails/focal.png",
    tech: ["Flutter", "Background Services"],
    github: "https://github.com/ShreyNagda/focal",
    live: "https://github.com/ShreyNagda/focal/releases/tag/release-01"
  },
  {
    tags: ["Fullstack", "Creative", "Web"],
    title: "Fraymer",
    desc: "Create beautiful retro-style photos in seconds",
    thumbnail: "/thumbnails/fraymer.png", // Using the clean mockup
    tech: ["Next JS", "TypeScript", "Tailwind CSS", "Html-to-Image"],
    github: "https://github.com/ShreyNagda/fraymer",
    live: "https://fraymer.vercel.app/",
  },
  {
    tags: ["AI", "Web"],
    title: "Tarotverse",
    desc: "AI-powered tarot reading and mysticism platform",
    thumbnail: "/thumbnails/tarotverse.png",
    tech: ["Next JS", "Gemini API", "Tailwind CSS"],
    github: "https://github.com/ShreyNagda/tarotverse",
    live: "https://tarotverse.vercel.app/",
  },
  // {
  //   tags: ["Productivity", "Web"],
  //   title: "Gamified Labs",
  //   desc: "An experiment in gamifying daily habits",
  //   thumbnail: "/thumbnails/gamified-labs.png",
  //   tech: ["React JS", "TypeScript", "Tailwind CSS"],
  //   github: "https://github.com/ShreyNagda/gamified-labs",
  // },
  {
    tags: ["Fullstack", "Web"],
    title: "SmartQuiz",
    desc: "An online quiz conducting platform",
    thumbnail: "/thumbnails/smartquiz.png",
    tech: ["Next JS", "Tailwind CSS", "Shadcn UI", "MongoDB"],
    github: "https://github.com/ShreyNagda/smartquiz-platform",
    live: "https://smartquiz-platform.vercel.app/",
  },
  {
    tags: ["Frontend", "Web"],
    title: "Kwizz",
    desc: "A trivia game fetching questions from OpenTDB",
    thumbnail: "/thumbnails/kwizz.png",
    tech: ["React JS", "Tailwind CSS", "OpenTDB API"],
    github: "https://github.com/ShreyNagda/kwizz-react",
    live: "https://kwizz-react.vercel.app/",
  },
  {
    tags: ["Content", "Web"],
    title: "Hackscript",
    desc: "A developer-focused blog and snippet library",
    thumbnail: "/thumbnails/hackscript.png",
    tech: ["Next JS", "Framer Motion", "Tailwind CSS"],
    github: "https://github.com/ShreyNagda/hackscript",
    live: "https://hackscript.vercel.app/",
  },
  {
    tags: ["Frontend", "Web"],
    title: "Exalt Website",
    desc: "Corporate website for a financial consultancy",
    thumbnail: "/thumbnails/exalt.gif",
    tech: ["React JS", "GSAP", "Tailwind CSS"],
    github: "https://github.com/ShreyNagda/exalt-website",
    live: "https://https://exalt.apsit.edu.in/",
  },
  {
    tags: ["Mobile", "Game"],
    title: "Guess Up",
    desc: "A mobile based charades game for party buffs",
    thumbnail: "/thumbnails/guessup.png",
    tech: ["Flutter", "Firebase"],
    github: "https://github.com/ShreyNagda/guess-up",
    live: "https://github.com/ShreyNagda/guess-up/releases/tag/Release-001",
  },
  {
    tags: ["AI", "Web"],
    title: "Insurease",
    desc: "AI-based Insurance Policy Analyzer ",
    thumbnail: "/thumbnails/insurease.png",
    tech: ["Next JS", "Tailwind CSS", "Huggingface Inference"],
    github: "https://github.com/ShreyNagda/insurease",
    live: "https://insurease-phi.vercel.app/",
  },
  {
    tags: ["Frontend", "Game"],
    title: "Hangman Game",
    desc: "A word guessing game",
    thumbnail: "/thumbnails/hangman.png",
    tech: ["React JS", "HTML 5", "CSS 3", "Dictionary API"],
    github: "https://github.com/ShreyNagda/hangman-game-react",
    live: "https://guess-or-hang.netlify.app/",
  },
];
